# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Room

# Model Form Field configuration
form: $/algad/hotel/models/room/fields.yaml

# Model Class name
modelClass: Algad\Hotel\Models\Room

# Default redirect location
defaultRedirect: algad/hotel/rooms

# Create page
create:
    title: Create Room
    redirect: algad/hotel/rooms/update/:id
    redirectClose: algad/hotel/rooms

# Update page
update:
    title: Edit Room
    redirect: algad/hotel/rooms
    redirectClose: algad/hotel/rooms

# Preview page
preview:
    title: Preview Room