# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/algad/hotel/models/room/columns.yaml

# Model Class name
modelClass: Algad\Hotel\Models\Room

# List Title
title: Manage Rooms

# Link URL for each record
recordUrl: algad/hotel/rooms/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: number
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
