# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Customer

# Model Form Field configuration
form: $/algad/hotel/models/customer/fields.yaml

# Model Class name
modelClass: Algad\Hotel\Models\Customer

# Default redirect location
defaultRedirect: algad/hotel/rooms

# Create page
create:
    title: Create Customer
    redirect: algad/hotel/customers/update/:id
    redirectClose: algad/hotel/customers

# Update page
update:
    title: Edit Customer
    redirect: algad/hotel/customers
    redirectClose: algad/hotel/customers

# Preview page
preview:
    title: Preview Customer